name: Delete preview on PR close

# only trigger on pull request closed events
on:
  pull_request:
    types: [closed]

jobs:
  delete_preview:
    runs-on: ubuntu-20.04
    env:
      PR_PATH: pull/${{github.event.number}}
    steps:
      - name: Make empty dir
        run: mkdir public

      - name: Delete folder
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          destination_dir: ${{ env.PR_PATH }}

      - name: Comment on PR
        uses: hasura/comment-progress@v2.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          number: ${{ github.event.number }}
          id: deploy-preview
          message: "PR closed. Deleted preview at https://github.com/${{ github.repository }}/tree/gh-pages/${{ env.PR_PATH }}/"
